Algoritmo "Idade"

Var
nome1: caractere
nome2: caractere
idade1: inteiro
idade2: inteiro
MediaTotal: real

Inicio
escreval("Dados da Primeira Pessoa: ")
escreva("Nome: ")
leia(nome1)

escreva("Idade: ")
leia(idade1)
escreval
escreval("Dados da Segunda Pessoa: ")
escreva("Nome: ")
leia(nome2)
escreva("Idade: ")
leia(idade2)

MediaTotal <- (idade1 + idade2)  / 2

escreva("A idade média de ", nome1, " e ", nome2, " é de ", MediaTotal, " anos." )

Fimalgoritmo