Algoritmo "multiplos"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/06/2021
Var
x, y: inteiro

Inicio
escreval("digite dois numeros inteiros: ")
leia(x)
leia(y)

se (x % y = 0) ou (y % x = 0) entao
   escreva ("sao multiplos")
senao
   escreva("nao sao multiplos")
fimse
Fimalgoritmo