Algoritmo "senha_fixa"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/06/2021
Var
senha: inteiro


Inicio
escreva("Escreva a Senha:")
leia(senha)


enquanto senha <> 2002 faca
   escreva("Senha inválida! Tente novamente: ")
   leia(senha)
   fimenquanto
   
   escreval("Acesso Permitido")


Fimalgoritmo