Algoritmo "sequencia_impares"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/06/2021
Var
a, b: inteiro

Inicio
a <- 0
b <- 0
escreva("Digite o valor de X: ")
leia(a)

para b de 1 ate a faca
   se b % 2 <> 0 entao
  escreval(b)
  fimse
fimpara


Fimalgoritmo