Algoritmo "Soma"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/06/2021
Var
valor1, valor2, total: inteiro


Inicio
escreva("Digite o valor de X: ")
leia(valor1)
escreva("Digite o valor de y: ")
leia(valor2)
total <- valor1 + valor2
escreva("Soma: ", total)

Fimalgoritmo