Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/06/2021
Var
a, b, resultado: inteiro

Inicio
escreva ("Escreva um nome de tabuada: ")
leia(a)

para b de 1 ate 10 faca

resultado<- a * b

escreval(a, " * ", b, " = ", resultado)


fimpara
Fimalgoritmo